"""fix_availability_date_instead_of_day_enum

Revision ID: 935d06557572
Revises: 853e3d183650
Create Date: 2026-04-22 11:13:55.676292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '935d06557572'
down_revision: Union[str, Sequence[str], None] = '853e3d183650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("availabilities", "day")
    op.add_column("availabilities", sa.Column("date", sa.Date(), nullable=False))
    op.execute("DROP TYPE IF EXISTS days_enum")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE days_enum AS ENUM ('MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY')")
    op.drop_column("availabilities", "date")
    op.add_column("availabilities", sa.Column("day", sa.Enum("MONDAY","TUESDAY","WEDNESDAY","THURSDAY","FRIDAY","SATURDAY","SUNDAY", name="days_enum"), nullable=False))
    # ### end Alembic commands ###
