"""add unique constraint availabilities

Revision ID: f380617ca620
Revises: 935d06557572
Create Date: 2026-04-30 00:41:51.201436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f380617ca620'
down_revision: Union[str, Sequence[str], None] = '935d06557572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_practitioner_date_start', 'availabilities', ['practitioner_id', 'date', 'start_time'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_practitioner_date_start', 'availabilities', type_='unique')
    # ### end Alembic commands ###
